Repository WebXDAO/blockchain-dev-path, pull requests merged in 2022-10, with the labels that each got.

#51 fixed the broken link of polygon academy
  docs/💖 Free Training/Polygon Academy.md
Labels: bug

#48 [Docs] : Update and improve readme files in Resources
  docs/🤩 Resources/Become a blockchain developer.md
  docs/🤩 Resources/Bitcoin working.md
  docs/🤩 Resources/Future of Web3.md
  docs/🤩 Resources/Guide to Full Stack Ethereum Development.md
  docs/🤩 Resources/Local Solidity Development.md
  docs/🤩 Resources/Roadmap to learn Blockchain development.md
  docs/🤩 Resources/Solidity, Blockchain, and Smart Contract Course.md
  docs/🤩 Resources/Stack NFT Marketplace on Ethereum with Polygon and Next.js.md
  docs/🤩 Resources/Web3 Stack.md
Labels: documentation

#53 Add Crypto Startup School Lectures to Resources Section
  docs/🤩 Resources/Crypto Startup School.md
Labels: enhancement
